# Generated by Django 6.0.2 on 2026-03-05 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Miniature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='miniatures/')),
                ('name', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('description', models.TextField()),
                ('painted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.faction')),
            ],
        ),
    ]
