# Generated by Django 6.0.2 on 2026-03-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miniature',
            name='painted',
        ),
        migrations.AddField(
            model_name='miniature',
            name='painting_stage',
            field=models.CharField(choices=[('unbuilt', 'Unbuilt'), ('built', 'Built'), ('primed', 'Primed'), ('painting', 'Painting'), ('finished', 'Finished')], default='unbuilt', max_length=20),
        ),
    ]
