# Generated by Django 6.0.2 on 2026-03-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='miniatures/'),
        ),
    ]
